### ISSUE TITLE
RFC: Document Baseline

### ISSUE THREAD

**Issue by avivace** [gbadev-org/gbadoc#4]
Which document should we use as a baseline?

- [CowBiteSpec](https://www.cs.rit.edu/~tjh8300/CowBite/CowBiteSpec.htm) *
- [GBAtek](https://problemkaputt.de/gbatek.txt)

Keep in mind we'll also need a permission enabling us to reuse. Items marked with * are already released with a permissive license.

**Comment by LunarLambda** [comment]
The ARM7TDMI manual / ARM ARM?

I was looking the other day if there was perhaps a reference manual for ARMv4T specifically, but it doesn't seem so.

Would have to look into what the licensing situation is around those. They're free to download, so at the very least we can link people to them.

**Comment by Lokathor** [comment]
(for reference: the CowBiteSpec was allowed for use here https://github.com/gbdev/gbadoc/issues/1#issuecomment-817118343)

**Comment by avivace** [comment]
I'd like to use CowBiteSpec as starting point, splitting in single files and starting to improve and work on that

**Comment by LunarLambda** [comment]
Since neither me or avivace are expecting to get an answer from Martin about GBATEK, and no other reference was brought up, I think we can considered this settled?

**Comment by avivace** [comment]
> Since neither me or avivace are expecting to get an answer from Martin about GBATEK, and no other reference was brought up, I think we can considered this settled?

Worst case we can add stuff fom gbatek later. I'd start importing CowBiteSpec here (but we first have to close https://github.com/gbdev/gbadoc/issues/2)

**Comment by Lokathor** [comment]
Yeah if we can agree on a tech stack then we can get writing.

I would suggest that we do not just wholesale import from cowbite. i think we can do a little better on the organization of things that way.

**Comment by avivace** [comment]
> Yeah if we can agree on a tech stack then we can get writing.
> 
> I would suggest that we do not just wholesale import from cowbite. i think we can do a little better on the organization of things that way.

I'd start importing and reformatting the content splitting the document so we can have a separate file per chapter, after the initial import we can re-organize the structure, step by step

**Comment by exelotl** [comment]
Initial import is now covered by #17!
